import defaultTheme from "tailwindcss/defaultTheme";
import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/views/**/*.blade.php",
        "./resources/assets/js/*.tsx",
        "./resources/assets/js/**/*.tsx",
        "./resources/assets/js/**/**/*.tsx",
        "./resources/assets/js/stories/*.stories.ts",
        "./resources/assets/js/stories/**/*.stories.ts",
        "./resources/assets/js/stories/**/**/*.stories.ts",
        "./node_modules/tailwind-datepicker-react/dist/**/*.js",
        "./node_modules/react-tailwindcss-datepicker/dist/index.esm.js",
    ],

    theme: {
        screens: {
            xxxs: "320px",
            xxs: "375px",
            xs: "425px",
            ...defaultTheme.screens,
            '3xl': '1600px',

        },
        extend: {
            ...defaultTheme,
            fontFamily: {
                sans: ["Figtree", ...defaultTheme.fontFamily.sans],
            },
            height: {
                "100vh": "100vh",
                "90vh": "90vh",
                "80vh": "80vh",
                "70vh": "70vh",
                "60vh": "60vh",
                "50vh": "50vh",
                "40vh": "40vh",
                "30vh": "30vh",
                "20vh": "20vh",
                "10vh": "10vh",
                "side-bar": "calc(100vh - 83px)",
                ...defaultTheme.height,
            },
            minWidth: {
                0: "0rem",
                none: "none",
                xxxs: "5rem",
                32: "8rem",
                36: "9rem",
                xxs: "10rem",
                48: "12rem",
                xs: "20rem",
                sm: "24rem",
                md: "28rem",
                lg: "32rem",
                xl: "36rem",
                "2xl": "42rem",
                "3xl": "48rem",
                "4xl": "56rem",
                "5xl": "64rem",
                "6xl": "72rem",
                "7xl": "80rem",
                full: "100%",
                min: "min-content",
                max: "max-content",
                fit: "fit-content",
                prose: "65ch",
                "screen-sm": "640px",
                "screen-md": "768px",
                "screen-lg": "1024px",
                "screen-xl": "1280px",
                "screen-2xl": "1536px",
                ...defaultTheme.minWidth,
            },
            minHeight: {
                0: "0rem",
                none: "none",
                xxxs: "5rem",
                xxs: "10rem",
                xs: "20rem",
                sm: "24rem",
                md: "28rem",
                lg: "32rem",
                xl: "36rem",
                "2xl": "42rem",
                "3xl": "48rem",
                "4xl": "56rem",
                "5xl": "64rem",
                "6xl": "72rem",
                "7xl": "80rem",
                full: "100%",
                min: "min-content",
                max: "max-content",
                fit: "fit-content",
                prose: "65ch",
                "screen-sm": "640px",
                "screen-md": "768px",
                "screen-lg": "1024px",
                "screen-xl": "1280px",
                "screen-2xl": "1536px",
                ...defaultTheme.minHeight,
            },
        },
    },

    plugins: [forms],
};
